### ISSUE TITLE
program_invocation_name is NULL

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#41]
A lot of programs get their own name by looking at program_invocation_name or program_invocation_short_name. Right now, those are NULL. Setting these correctly would fix this.

**Comment by avdgrinten** [comment]
This can be fixed by changing managarm's sysdeps to use the generic ELF entry code. Ironically, managarm seems to be the only port that does not use the generic code.

Generic code: https://github.com/managarm/mlibc/blob/master/sysdeps/linux/generic/entry.cpp#L25
Managarm's code: https://github.com/managarm/mlibc/blob/master/sysdeps/managarm/generic/entry.cpp#L124
