### ISSUE TITLE
Implement the `syscall` macro on Linux

### ISSUE THREAD

**Issue by 64** [managarm/mlibc#523]
Given that the alternative is patching everything, this is probably the best option. We might be able to rip this from musl, or maybe it'd be not too hard to implement ourselves.

**Comment by sskras** [comment]
> We might be able to rip this from musl

Since discussions aren't enabled for this repo, I thought that would be a appropriate place to ask:

How is mlibc different from musl? Wasn't musl portable enough? What's the point?

**Comment by avdgrinten** [comment]
musl is not portable at all and limited to Linux. Pinging 14 people on a random issue violates basic internet etiquette and won't be tolerated.

**Comment by no92** [comment]
Pinging 14 contributors for a question is wildly rude.

**Comment by ArsenArsen** [comment]
> > We might be able to rip this from musl
> 
> Since discussions aren't enabled for this repo, I thought that would be a appropriate place to ask:
> 
> How is mlibc different from musl? Wasn't musl portable enough? What's the point?

musl isn't portable at all? it specifically presumes linux, and hardcodes Linux syscalls. which is fine.

glibc is more comparable to mlibc in terms of portability.

**Comment by saukrs** [comment]
(answering from my business account since you blocked the original one)

> Pinging 14 people on a random issue violates basic internet etiquette and won't be tolerated.

@avdgrinten, excuse me please. There is seemingly no appropriate place in this repo to ask questions like this. That's why I chose the closed issue so it won't ruin any existing workflow. 

I also removed the ping-comment.

> Pinging 14 contributors for a question is wildly rude.

That's because I found no information about contacting the project lead. Without knowing whom to contact how otherwise should I proceed?

Also thanks to both members who answered my question directly and clearly. No offense.

**Comment by Dennisbonke** [comment]
> (answering from my business account since you blocked the original one)
> 
> > Pinging 14 people on a random issue violates basic internet etiquette and won't be tolerated.
> 
> @avdgrinten, excuse me please. There is seemingly no appropriate place in this repo to ask questions like this. That's why I chose the closed issue so it won't ruin any existing workflow. 
> 
> I also removed the ping-comment.
> 
> > Pinging 14 contributors for a question is wildly rude.
> 
> That's because I found no information about contacting the project lead. Without knowing whom to contact how otherwise should I proceed?
> 
> Also thanks to both members who answered my question directly and clearly. No offense.

One could've joined the discord, which is listed in the readme? Or our IRC channels, although they are not mentioned in the readme for mlibc itself.

**Comment by ArsenArsen** [comment]
project discussions are open now, and the readme lists a discord server (and should list `#managarm-mlibc` on Libera.Chat but apparently we forgot to list it), so the latter could work for such discussion

**Comment by no92** [comment]
> There is seemingly no appropriate place in this repo to ask questions like this. That's why I chose the closed issue [..]
There is, as pointed out by others, the Discord (and the unlisted IRC). Or a new issue. Necroing an unrelated issue is bad manners.

> That's because I found no information about contacting the project lead. Without knowing whom to contact how otherwise should I proceed?
The issue tracker is plenty enough. If comments are posted on here, contributors will see it and reply in time - which might be a few hours or days. Have some patience.

Regardless, why do you need to ping a project lead for a question? Is the rest of us not good enough for you?

> I also removed the ping-comment.
This does not undo it.

We are not obliged to answer to anyone, especially if their conduct is this disrespectful. The ban evasion with an alt does not do you any favors.

For posterity, this is bad etiquette:
- necroing a 4-year old issue
- with an unrelated question
- waiting minutes before pinging 14 contributors, because apparently you are just that important as to bother this many people
- getting blocked, evading with an alt
- needing to talk to the project lead specifically for a general question
- diluting their apology with excuses

Speaking for myself, please do not interact until your internet manners have caught up.
